spring:
  datasource:
    url: jdbc:tc:postgresql:16:///flashcards_test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: test
    password: test
  flyway:
    enabled: true
